### ISSUE TITLE
package distribution

### ISSUE THREAD

**Issue by ptbrown1729** [jacobkimmel/ps_decomp#1]
I have found this code very useful, and I have some code on a (soon to be) public git repo that depends on it. It would be great if there were an easy way to pip install it so I can include it in my requirements.txt file. My understanding is to do that there needs to be a setup.py file make it a "package". Is that something you would consider putting together? I would be happy to help if that is useful.

**Comment by AndrewGYork** [comment]
Hey awesome! That makes me really happy to hear. Sounds reasonable to me. @jacobkimmel, thoughts? I know this guy, and I like him.

Although if I were you, Peter, I would be tempted to copy-paste the relevant ~60 lines of code into your project, rather than pick up an external dependency. An in-line link back to this repo might be a nice form of attribution if you choose that approach.

**Comment by ptbrown1729** [comment]
That's a good idea too, thanks!

**Comment by jacobkimmel** [comment]
As @AndrewGYork says, please feel free to just copy/paste this module into your package with a comment listing the source. That way, you're never dependent on me & Andy of all people.

I'm also happy to make a package if that's easier given your needs.
Just let me know if that's your preferred method.

Glad you found this useful!

**Comment by ptbrown1729** [comment]
Great, I will go ahead and copy/paste into my package. Thanks!
